language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -print0 | xargs -0 rm -rvf
cache:
  directories:
  - $HOME/.ckfinder
  - $HOME/.m2
install: true
jdk: openjdk14
script: .travis/publish.sh "-Dckfinder.cache.directory=$HOME/.ckfinder"
after_success:
- bash <(curl -s https://codecov.io/bash)
