language: java
before_cache:
- ./mvnw build-helper:remove-project-artifact
- find $HOME/.m2/ -type d -name '*-SNAPSHOT' -exec rm -rf {} \; 2>/dev/null
cache:
  directories:
  - $HOME/.ckfinder
  - $HOME/.m2
jdk: oraclejdk8
install: true
script: .travis/publish.sh "-Dckfinder.cache.directory=$HOME/.ckfinder"
after_success:
- bash <(curl -s https://codecov.io/bash)
