name: build

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      java-version:
        type: choice
        description: java version to deploy to sonatype snapshot repository
        required: false
        options:
          - skip
          - '8'
          - '11'

jobs:
  build:
    name: build with jdk ${{ matrix.java-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version:
          - 8
          - 11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v2
        env:
          cache-name: maven-dependencies
        with:
          path: |
            ~/.m2/ckfinder
            ~/.m2/repository
          key: ${{ env.cache-name }}-${{ github.workflow }}-${{ hashFiles('.github/**', '**/pom.xml') }}
          restore-keys: |
            ${{ env.cache-name }}-${{ github.workflow }}-
            ${{ env.cache-name }}-
      - name: mvnw install
        run: ./mvnw -B --color=always "-Dckfinder.cache.directory=$HOME/.m2/ckfinder" install
      - name: Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
      - name: Before Cache
        run: |
          ./mvnw -B --color=always build-helper:remove-project-artifact || :
          find ~/.m2/ -type d -name '*-SNAPSHOT' \( -exec rm -rf '{}' \; -prune \)
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && github.repository == 'zhanhb/ckfinder-spring-boot' && github.ref_name == 'master' ||
      github.event_name == 'workflow_dispatch' && github.event.inputs.java-version > 0
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ github.event.inputs.java-version || '11' }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven Deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          version="$(./mvnw -B -N help:evaluate -Dexpression=project.version -q -DforceStdout)"
          case "$version" in
          *-SNAPSHOT) ./mvnw -B --color=always "-Dckfinder.cache.directory=$HOME/.m2/ckfinder" deploy ;;
          *) printf '\e[31m%s\e[m\n' "skip deploy version '$version'" ;;
          esac
      - name: Before Cache
        run: |
          ./mvnw -B --color=always build-helper:remove-project-artifact || :
          find ~/.m2/ -type d -name '*-SNAPSHOT' \( -exec rm -rf '{}' \; -prune \)
